version: '3.8'
services:
  dotnet_postgres:
    image: postgres:alpine
    container_name: dotnet_postgres
    restart: always
    environment:
      POSTGRES_DB: dotnet
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 123
    ports:
      - '5432:5432'
    
  dotnet_rabbitmq:
    image: rabbitmq:3-alpine
    
  dotnet_minio:
    image: minio/minio:latest
    
  dotnet_mongodb:
    image: mongo:latest
    
  dotnet_jaeger:
    image: jaegertracing/all-in-one:latest
    
  dotnet_main:
    image: dotnet-web
    container_name: dotnet_main
    ports:
      - "5000:5000"
    build:
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    depends_on:
      - dotnet_postgres
    environment:
      ConnectionStrings__Default: Host=localhost;Database=dotnet;Port=5432;Username=dev;Password=123
      
  dotnet_mailing:
    image: dotnet-web
    
  dotnet_storage:
    image: dotnet-web
  dotnet.homeworks.mainproject:
    image: dotnet.homeworks.mainproject
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
